name: build googleads-rs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get -y install protobuf-compiler
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get -y install protobuf-compiler
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Install cargo2junit
      uses: taiki-e/install-action@cargo2junit
    - name: Generate coverage and JUnit XML
      run: |
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        cargo2junit > junit.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: lcov.info
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: junit.xml

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get -y install protobuf-compiler
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: choco install protoc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose